### ISSUE TITLE
Capital Manufacturing drop down showing only sub capitals

### ISSUE THREAD

**Issue by PocketPicknam** [Ramit110/Ramit110.github.io#10]
**Describe the bug**
Capital Manufacturing drop down showing only sub capitals

**To Reproduce**
1. Go to 'Capital Manufacturing'
2. Click on 'Select Ship'
3. See error

**Expected behavior**
Capital Ships listed

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [up to date?]

**Comment by Ramit110** [comment]
Fixed in 498f96f
