### ISSUE TITLE
Include Volume

### ISSUE THREAD

**Issue by Ramit110** [Ramit110/Ramit110.github.io#2]
More particularly to the ore calculator.

**Comment by Ravandel95** [comment]
Yeah so i was thinking, if the Ores are more expensive than the t1 minerals, it may be better to straightup haul in minerals, than compressed ores, if there is sufficient volume left over.

So what you could do, is allow it to not only select the compressed ores to buy, but also t1 minerals.
And then you can add a constraint which says that the resulting volume should not be larger than some target volume.

**Comment by Ramit110** [comment]
>  And then you can add a constraint which says that the resulting volume should not be larger than some target volume.

This one can probably be defined by the user, set it to -1 if volume doesn't matter or something
