### ISSUE TITLE
Rav's wishlist #1: buy/sell prices 

### ISSUE THREAD

**Issue by Ravandel95** [Ramit110/Ramit110.github.io#3]
Would be nice if it displays both the sell prices and the buy prices for the computed ore's.

Also technically the sell-price based optimal solution may be different than the buy-price based one. 
So you may want to put in a tickbox to choose which you want to minimize.

**Comment by Ramit110** [comment]
- [x] Would be nice if it displays both the sell prices and the buy prices for the computed ore's.

- [X] Also technically the sell-price based optimal solution may be different than the buy-price based one.

- [ ] So you may want to put in a tickbox to choose which you want to minimize.

**Comment by Ramit110** [comment]
Next version will have the above ticked

Not sure it's needed though I'll do it anyway soon enough.
TODO: ?
- [ ]  So you may want to put in a tickbox to choose which you want to minimize.

**Comment by Ravandel95** [comment]
Yeah normally i'd say that this is not really needed.
But given how f'd the ore market is atm, the buy and sell prices can be quite different

**Comment by Ramit110** [comment]
Is this still needed @Ravandel95?
