### ISSUE TITLE
Rav's wishlist #2: Select which ores it may use

### ISSUE THREAD

**Issue by Ravandel95** [Ramit110/Ramit110.github.io#4]
So i've noticed that some ores barely get sold in the Jita market, eventhough the prices on them are decent.

Specifically to build a few Dreadnoughts it told me to buy 2000 Compressed Hemorphite.
The Jita market however, only had about 1500 Compressed Hemorphite available.

The easiest way to get around this, is likely to allow the user to tickbox out which ores the solver is allowed to use.

**Comment by Ramit110** [comment]
Done in https://github.com/Ramit110/Ramit110.github.io/commit/604f11cbd06981e87f78c12fc5535413f0f8ab60
