### ISSUE TITLE
Support for Faction Capital Blueprints

### ISSUE THREAD

**Issue by PocketPicknam** [Ramit110/Ramit110.github.io#8]
**Is your feature request related to a problem? Please describe.**
Was looking for info on faction capital bpc production under your Capital Manufacturing tab and realized that you don't have any of the faction capitals listed.

**Describe the solution you'd like**
Just curious if you intend to add faction capital support on your page or not, I know certain capital bpc's are relatively easy to come by (vehement/vendetta) with faction loyalty points and it would be nice to see what it would cost if one were to place buy orders to acquire the necessary materials to construct one.

**Describe alternatives you've considered**
N/A

**Additional context**

![fix](https://user-images.githubusercontent.com/66314997/83525015-430b7f80-a499-11ea-8f61-e91b0ac7c62e.jpg)

**Comment by Ramit110** [comment]
Oh, this is a complete oversight from me, I'll have them added soon.

**Comment by Ramit110** [comment]
Done in fc7f34ecd29bf8f1ae6d8fb7313d7418da363631
